org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US --enable-native-access=ALL-UNNAMED 

pluginName = SmartTomcat
pluginGroup = com.poratu.idea.plugins.tomcat
pluginVersion = 4.8.0

pluginSinceBuild = 242.26775
#pluginUntilBuild=

platformVersion = 2025.2.4

jdkVersion = 25
compatibleJdkVersion = 17

gradleVersion = 9.3.1