org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US

pluginName = SmartTomcat
pluginGroup = com.poratu.idea.plugins.tomcat
pluginVersion = 4.8.0

pluginSinceBuild = 2022.1
pluginUntilBuild=

platformType = IC
platformVersion = 2025.3

jdkVersion = 21
compatibleJdkVersion = 17
gradleVersion = 7.5.1

platformPlugins = com.intellij.java

kotlin.stdlib.default.dependency = false
